INSERT INTO category(description) VALUES ('American');
INSERT INTO category(description) VALUES ('Tigrian');
INSERT INTO category(description) VALUES ('Eritrean');
INSERT INTO category(description) VALUES ('Ethiopian');
INSERT INTO unit_of_measure(description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure(description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure(description) VALUES ('Cup');
INSERT INTO unit_of_measure(description) VALUES ('Pinch');
INSERT INTO unit_of_measure(description) VALUES ('Ounce');
